apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "screeps.fullname" . }}
  labels:
{{ include "screeps.labels.standard" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "screeps.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ template "screeps.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        {{- if .Values.persistence.mounts }}
{{ toYaml .Values.persistence.mounts | indent 8 }}
        {{- end }}
        {{- if .Values.config }}
        - name: config
          mountPath: /screeps/config.yml
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
        envFrom:
        {{- range .Values.envSecrets }}
        - secretRef:
            name: {{ . }}
        {{- end }}
      volumes:
{{- if .Values.persistence.volumes }}
{{ tpl (toYaml .Values.persistence.volumes | indent 6) . }}
{{- end }}
      {{- if .Values.config }}
      - name: config
        configMap:
          name:
          items:
          - key: config.yaml
            path: keys
      {{- end }}
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "screeps.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
