apiVersion: v2
name: screeps
description: A standalone server for programming game Screeps

type: application
version: 1.0.5

dependencies:
- name: redis
  version: 17.3.11
  condition: redis.enabled
  repository: https://charts.bitnami.com/bitnami
- name: mongodb
  version: 13.5.0
  condition: mongodb.enabled
  repository: https://charts.bitnami.com/bitnami